In [1]:
import numpy as np 

### Task 1 Solution 


##### Tranformation Matrix of the camera with respect to the base frame 

In [2]:
T_camera_wrt_base = np.array([[-1,0,1,0],
                            [0,0 ,-1 ,-0.7],
                            [0,-1,0,0.7],
                            [0,0,0,1]])
T_camera_wrt_base

array([[-1. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. , -1. , -0.7],
       [ 0. , -1. ,  0. ,  0.7],
       [ 0. ,  0. ,  0. ,  1. ]])

##### Transformation Matrix of the workpiece with respect to camera frame 

In [3]:
T_wp_wrt_camera = np.array([[0.93,-0.353,0.0669,0.2],
                            [0.3535,0.8660 ,-0.35355 ,0],
                            [0.669783,0.35355,0.9330,0.5],
                            [0,0,0,1]])
T_wp_wrt_camera

array([[ 0.93    , -0.353   ,  0.0669  ,  0.2     ],
       [ 0.3535  ,  0.866   , -0.35355 ,  0.      ],
       [ 0.669783,  0.35355 ,  0.933   ,  0.5     ],
       [ 0.      ,  0.      ,  0.      ,  1.      ]])

##### Poistion of h1 with respect to the workpiece 

In [4]:
T_h1 = np.array([[1,0,0,0.2],
                [0,1,0,0.2],
                [0,0,1,0],
                [0,0,0,1]])

In [5]:
T_h1_wrt_base = np.matmul((np.matmul(T_camera_wrt_base,T_wp_wrt_camera)),T_h1)
T_h1_wrt_base

array([[-0.260217 ,  0.70655  ,  0.8661   ,  0.3892666],
       [-0.669783 , -0.35355  , -0.933    , -1.4046666],
       [-0.3535   , -0.866    ,  0.35355  ,  0.4561   ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [10]:
T_h2 = np.array([[1,0,0,0.2],
                [0,1,0,-0.2],
                [0,0,1,0],
                [0,0,0,1]])
T_h2

array([[ 1. ,  0. ,  0. ,  0.2],
       [ 0. ,  1. ,  0. , -0.2],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [13]:
T_h2_wrt_base = np.matmul((np.matmul(T_camera_wrt_base,T_wp_wrt_camera)),T_h2)
T_h2_wrt_base

array([[-0.260217 ,  0.70655  ,  0.8661   ,  0.1066466],
       [-0.669783 , -0.35355  , -0.933    , -1.2632466],
       [-0.3535   , -0.866    ,  0.35355  ,  0.8025   ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [11]:
T_h3 = np.array([[1,0,0,-0.2],
                [0,1,0,0.2],
                [0,0,1,0],
                [0,0,0,1]])
T_h3

array([[ 1. ,  0. ,  0. , -0.2],
       [ 0. ,  1. ,  0. ,  0.2],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [14]:
T_h3_wrt_base = np.matmul((np.matmul(T_camera_wrt_base,T_wp_wrt_camera)),T_h3)
T_h3_wrt_base

array([[-0.260217 ,  0.70655  ,  0.8661   ,  0.4933534],
       [-0.669783 , -0.35355  , -0.933    , -1.1367534],
       [-0.3535   , -0.866    ,  0.35355  ,  0.5975   ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [12]:
T_h4 = np.array([[1,0,0,-0.2],
                [0,1,0,-0.2],
                [0,0,1,0],
                [0,0,0,1]])
T_h4

array([[ 1. ,  0. ,  0. , -0.2],
       [ 0. ,  1. ,  0. , -0.2],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [15]:
T_h4_wrt_base = np.matmul((np.matmul(T_camera_wrt_base,T_wp_wrt_camera)),T_h4)
T_h4_wrt_base

array([[-0.260217 ,  0.70655  ,  0.8661   ,  0.2107334],
       [-0.669783 , -0.35355  , -0.933    , -0.9953334],
       [-0.3535   , -0.866    ,  0.35355  ,  0.9439   ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

##### The same should be done for holes 2,3,4 

#### Task2 

In [6]:
T_h1_wrt_camera = np.array([[1,0,0,0],
                            [0,1,0,0],
                            [0,0,1,0.1],
                            [0,0,0,1]])
T_h1_wrt_camera

array([[1. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 1. , 0.1],
       [0. , 0. , 0. , 1. ]])

In [7]:
T_h1_wrt_camera_inv= np.linalg.inv(T_h1_wrt_camera)
T_h1_wrt_camera_inv

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. , -0.1],
       [ 0. ,  0. ,  0. ,  1. ]])

In [8]:
T_new_camera_wrt_base = np.matmul(T_h1_wrt_base,T_h1_wrt_camera_inv)
T_new_camera_wrt_base

array([[-0.260217 ,  0.70655  ,  0.8661   ,  0.3026566],
       [-0.669783 , -0.35355  , -0.933    , -1.3113666],
       [-0.3535   , -0.866    ,  0.35355  ,  0.420745 ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])